<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/stock.proto

namespace MuenchDev\GrpcDemo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>stock.StockUpdateRequest</code>
 */
class StockUpdateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string source_code = 1;</code>
     */
    protected $source_code = '';
    /**
     * Generated from protobuf field <code>string sku = 2;</code>
     */
    protected $sku = '';
    /**
     * Generated from protobuf field <code>float qty = 3;</code>
     */
    protected $qty = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source_code
     *     @type string $sku
     *     @type float $qty
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Stock::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string source_code = 1;</code>
     * @return string
     */
    public function getSourceCode()
    {
        return $this->source_code;
    }

    /**
     * Generated from protobuf field <code>string source_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sku = 2;</code>
     * @return string
     */
    public function getSku()
    {
        return $this->sku;
    }

    /**
     * Generated from protobuf field <code>string sku = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSku($var)
    {
        GPBUtil::checkString($var, True);
        $this->sku = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float qty = 3;</code>
     * @return float
     */
    public function getQty()
    {
        return $this->qty;
    }

    /**
     * Generated from protobuf field <code>float qty = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setQty($var)
    {
        GPBUtil::checkFloat($var);
        $this->qty = $var;

        return $this;
    }

}

