<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/stock.proto

namespace GPBMetadata\Protos;

class Stock
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a94020a1270726f746f732f73746f636b2e70726f746f120573746f636b22430a1253746f636b5570646174655265717565737412130a0b736f757263655f636f6465180120012809120b0a03736b75180220012809120b0a0371747918032001280222220a1353746f636b557064617465526573706f6e7365120b0a0361636b180120012808324a0a0553746f636b12410a0655706461746512192e73746f636b2e53746f636b557064617465526571756573741a1a2e73746f636b2e53746f636b557064617465526573706f6e73652200423a5a236769746875622e636f6d2f636d75656e63682f677270632d64656d6f2f70726f746f73ca02124d75656e63684465765c4772706344656d6f620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

